/**
 * cindy-bridge —— 写进 pi agentHome/extensions/ 的扩展源码(字符串常量)。
 *
 * 这段代码跑在 **pi 子进程**(bun runtime)里,不能 import cindy 任何模块;
 * 只依赖 pi 的 ExtensionAPI、fetch 与 node:fs。职责:
 *  1. 权限门:tool_call 拦截。bypassPermissions 放行;ask 档下只读内置工具放行,
 *     其余(bash/edit/write + 全部桥接 MCP 工具)经 ctx.ui.confirm 走 cindy 审批
 *     (RPC 模式 → extension_ui_request → PiAgent → interactionResolver)。
 *     权限档从 CINDY_PI_PERMISSION_FILE 每次现读 —— setPermissionMode 热切换生效;
 *     读不到一律按 ask(fail-closed)。
 *  2. MCP 桥:CINDY_PI_MCP_BRIDGE(JSON {token, servers[{name,url}]})指向 host 的
 *     localhost streamable-HTTP MCP bridge;对每个 server 走 initialize →
 *     tools/list,把工具注册成 pi 工具(mcp__<server>__<tool>),execute 转发
 *     tools/call。
 *  3. 会话树:注册 Cindy 私有 command，把 RPC prompt 桥到 ctx.navigateTree。
 *
 * 协议说明(@modelcontextprotocol/sdk StreamableHTTPServerTransport):
 *  - POST 单条 JSON-RPC;Accept 必须同时含 application/json 与 text/event-stream;
 *  - initialize 响应头 mcp-session-id,后续请求回带;
 *  - 响应可能是 application/json 或 SSE(请求-响应模式下 server 发完即关流,
 *    text() 可整体读取后解析);notification 返回 202 空体。
 *
 * 更新方式:PiAgent 每次 startSession 覆写该文件;改这里 = 改下次会话的桥行为。
 */

export const CINDY_BRIDGE_EXTENSION_FILENAME = 'cindy-bridge.ts';

export const CINDY_BRIDGE_EXTENSION_SOURCE = String.raw`/**
 * cindy-bridge (generated by Cindy — do not edit; overwritten on session start)
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';

const PERMISSION_TITLE = 'cindy:permission';
const READONLY_BUILTINS = new Set(['read', 'grep', 'find', 'ls']);
const FILE_WRITE_BUILTINS = new Set(['edit', 'write']);

// 凭证/密钥路径特征 —— 与 maker-core shared/auto-review.ts 的 CREDENTIAL_PATH_PATTERNS
// 保持同步(bridge 自包含,不能 import;改那边记得改这边)。只读工具入参命中即不再
// 直通,升级走 Cindy 审批:读 ~/.ssh、~/.aws 等即使是"只读"也是侦察面。
const CREDENTIAL_PATH_PATTERNS = [
  /(?:^|[\\/\s'"~])\.(?:ssh|aws|gnupg|kube|docker|claude|codex)\b/i,
  /(?:^|[\\/\s'"~])\.(?:netrc|npmrc|pgpass|pypirc)\b/i,
  /\bapplication_default_credentials\b/i,
  /\bcredentials\.json\b/i,
  /[\\/](?:codex|claude|gcloud)[\\/]auth\.json\b/i,
  /\/proc\/[^\s]*\/environ\b/i,  // /proc/self/environ、/proc/<pid>/environ、/proc/<pid>/task/<tid>/environ
  /\bid_rsa\b|\bid_ed25519\b|\bid_ecdsa\b|\bid_dsa\b|\.pem\b|\.p12\b/i,
];

// 递归扫全部字符串叶子(含数组 / 嵌套对象),深度上限防环/超大入参。工具入参把路径
// 放进 { paths: [...] } 或 { opts: { path } } 时也能命中,不止顶层 string 字段。
function touchesCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(input));
  if (Array.isArray(input)) return input.some((v) => touchesCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => touchesCredentialPath(v, depth + 1));
  }
  return false;
}

function currentPermissionState(): {
  mode: 'ask' | 'bypassPermissions';
  readOnlyRoots: string[];
} {
  const file = process.env.CINDY_PI_PERMISSION_FILE ?? '';
  if (!file) return { mode: 'ask', readOnlyRoots: [] };
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    return {
      mode: parsed?.mode === 'bypassPermissions' ? 'bypassPermissions' : 'ask',
      readOnlyRoots: Array.isArray(parsed?.readOnlyRoots)
        ? parsed.readOnlyRoots.filter((root: unknown) => typeof root === 'string')
        : [],
    };
  } catch {
    return { mode: 'ask', readOnlyRoots: [] };
  }
}

function isInsideRoot(candidate: string, root: string): boolean {
  const target = path.resolve(candidate);
  const base = path.resolve(root);
  const rel = path.relative(base, target);
  return rel === '' || (!rel.startsWith('..' + path.sep) && rel !== '..' && !path.isAbsolute(rel));
}

// ── MCP streamable-HTTP 极简 client ─────────────────────────────────────────

interface McpServerRef {
  name: string;
  url: string;
}

class McpHttpClient {
  private nextId = 1;
  private sessionId: string | null = null;

  constructor(
    private readonly server: McpServerRef,
    private readonly token: string,
  ) {}

  private headers(): Record<string, string> {
    const h: Record<string, string> = {
      'content-type': 'application/json',
      accept: 'application/json, text/event-stream',
      authorization: 'Bearer ' + this.token,
    };
    if (this.sessionId) h['mcp-session-id'] = this.sessionId;
    return h;
  }

  private async post(body: unknown): Promise<Response> {
    const res = await fetch(this.server.url, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify(body),
    });
    const sid = res.headers.get('mcp-session-id');
    if (sid) this.sessionId = sid;
    return res;
  }

  /** 解析 application/json 或 SSE 响应体里 id 匹配的 JSON-RPC response。 */
  private async readResponse(res: Response, id: number): Promise<any> {
    const contentType = res.headers.get('content-type') ?? '';
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error('MCP HTTP ' + res.status + ': ' + text.slice(0, 300));
    }
    if (contentType.includes('text/event-stream')) {
      const text = await res.text();
      for (const chunk of text.split('\n\n')) {
        for (const line of chunk.split('\n')) {
          if (!line.startsWith('data:')) continue;
          try {
            const msg = JSON.parse(line.slice(5).trim());
            if (msg && msg.id === id && ('result' in msg || 'error' in msg)) return msg;
          } catch {
            /* keep scanning */
          }
        }
      }
      throw new Error('MCP SSE response missing id=' + id);
    }
    return res.json();
  }

  async request(method: string, params?: unknown): Promise<any> {
    const id = this.nextId++;
    const res = await this.post({ jsonrpc: '2.0', id, method, ...(params !== undefined ? { params } : {}) });
    const msg = await this.readResponse(res, id);
    if (msg.error) {
      throw new Error('MCP ' + method + ' failed: ' + (msg.error.message ?? JSON.stringify(msg.error)));
    }
    return msg.result;
  }

  async notify(method: string, params?: unknown): Promise<void> {
    await this.post({ jsonrpc: '2.0', method, ...(params !== undefined ? { params } : {}) }).catch(() => {});
  }

  async initialize(): Promise<void> {
    await this.request('initialize', {
      protocolVersion: '2025-03-26',
      capabilities: {},
      clientInfo: { name: 'cindy-pi-bridge', version: '1.0.0' },
    });
    await this.notify('notifications/initialized');
  }
}

function mcpContentToPi(content: unknown): Array<Record<string, unknown>> {
  const out: Array<Record<string, unknown>> = [];
  if (Array.isArray(content)) {
    for (const item of content) {
      if (!item || typeof item !== 'object') continue;
      const rec = item as Record<string, unknown>;
      if (rec.type === 'text' && typeof rec.text === 'string') {
        out.push({ type: 'text', text: rec.text });
      } else if (rec.type === 'image' && typeof rec.data === 'string') {
        out.push({ type: 'image', data: rec.data, mimeType: rec.mimeType ?? 'image/png' });
      } else {
        out.push({ type: 'text', text: JSON.stringify(rec) });
      }
    }
  }
  if (out.length === 0) out.push({ type: 'text', text: '(empty result)' });
  return out;
}

async function connectServer(pi: any, server: McpServerRef, token: string): Promise<number> {
  const client = new McpHttpClient(server, token);
  await client.initialize();
  const listed = await client.request('tools/list', {});
  const tools: any[] = Array.isArray(listed?.tools) ? listed.tools : [];
  for (const tool of tools) {
    const qualifiedName = 'mcp__' + server.name + '__' + tool.name;
    const parameters =
      tool.inputSchema && typeof tool.inputSchema === 'object'
        ? tool.inputSchema
        : { type: 'object', properties: {}, additionalProperties: true };
    try {
      pi.registerTool({
        name: qualifiedName,
        label: server.name + ': ' + tool.name,
        description: typeof tool.description === 'string' && tool.description.length > 0
          ? tool.description
          : 'MCP tool ' + tool.name + ' from ' + server.name,
        parameters,
        async execute(_toolCallId: string, params: unknown) {
          const result = await client.request('tools/call', {
            name: tool.name,
            arguments: params ?? {},
          });
          const content = mcpContentToPi(result?.content);
          if (result?.isError) {
            const text = content
              .map((c) => (typeof c.text === 'string' ? c.text : ''))
              .join('\n')
              .trim();
            throw new Error(text.length > 0 ? text : 'MCP tool ' + tool.name + ' failed');
          }
          return { content, details: result?.structuredContent ?? {} };
        },
      });
    } catch (err) {
      console.error('[cindy-bridge] register ' + qualifiedName + ' failed: ' + String(err));
    }
  }
  return tools.length;
}

export default async function cindyBridge(pi: any) {
  // ── 原生会话树桥 ──────────────────────────────────────────────────────────
  // RPC 没有 navigate_tree command；ExtensionCommandContext 才暴露 navigateTree。
  // 参数用 percent-encoded JSON，避免 prompt 命令的空格/斜杠解析污染 payload。
  pi.registerCommand('cindy-branch-switch', {
    description: 'Cindy internal session branch navigation',
    handler: async (args: string, ctx: any) => {
      let payload: {
        entryId?: unknown;
        summarize?: unknown;
        customInstructions?: unknown;
        label?: unknown;
      };
      try {
        payload = JSON.parse(decodeURIComponent(args.trim()));
      } catch {
        throw new Error('Invalid Cindy branch payload');
      }
      if (typeof payload.entryId !== 'string' || payload.entryId.length === 0 || payload.entryId.length > 128) {
        throw new Error('Invalid Cindy branch entry id');
      }
      const customInstructions = typeof payload.customInstructions === 'string'
        ? payload.customInstructions.trim().slice(0, 4000)
        : undefined;
      const label = typeof payload.label === 'string'
        ? payload.label.trim().slice(0, 120)
        : undefined;
      await ctx.waitForIdle();
      await ctx.navigateTree(payload.entryId, {
        summarize: payload.summarize === true,
        ...(customInstructions ? { customInstructions } : {}),
        ...(label ? { label } : {}),
      });
    },
  });

  // ── 权限门 ────────────────────────────────────────────────────────────────
  pi.on('tool_call', async (event: any, ctx: any) => {
    const permission = currentPermissionState();
    // Extra Dirs 的结构化写工具永远禁止，即使 Full access 也不能把“只读引用”静默
    // 升级成写目录。bash 仍由 Cindy 审批/模型指令约束（Pi 暂无 OS sandbox API）。
    const targetPath = typeof event.input?.path === 'string' ? event.input.path : '';
    if (
      targetPath
      && FILE_WRITE_BUILTINS.has(event.toolName)
      && permission.readOnlyRoots.some((root) => isInsideRoot(targetPath, root))
    ) {
      return { block: true, reason: 'Cindy extra reference directories are read-only.' };
    }
    if (permission.mode === 'bypassPermissions') return;
    if (READONLY_BUILTINS.has(event.toolName) && !touchesCredentialPath(event.input)) return;
    let approved = false;
    try {
      approved = await ctx.ui.confirm(
        PERMISSION_TITLE,
        JSON.stringify({ toolName: event.toolName, input: event.input ?? {} }),
      );
    } catch {
      approved = false;
    }
    if (!approved) {
      return { block: true, reason: 'User denied this tool call via Cindy.' };
    }
  });

  // ── MCP 桥 ────────────────────────────────────────────────────────────────
  const raw = process.env.CINDY_PI_MCP_BRIDGE;
  if (!raw) return;
  let cfg: { token?: string; servers?: McpServerRef[] };
  try {
    cfg = JSON.parse(raw);
  } catch {
    console.error('[cindy-bridge] invalid CINDY_PI_MCP_BRIDGE JSON');
    return;
  }
  const token = cfg.token ?? '';
  for (const server of cfg.servers ?? []) {
    try {
      const count = await connectServer(pi, server, token);
      console.error('[cindy-bridge] connected ' + server.name + ' (' + count + ' tools)');
    } catch (err) {
      console.error('[cindy-bridge] connect ' + server.name + ' failed: ' + String(err));
    }
  }
}
`;
