/**
 * 预览文档的 CSP:策略内容、注入位置,以及「策略必须挂在渲染载体上」的接线守卫。
 *
 * 资源透传相关的接线守卫(签名地址不得进页面、OSS 对象回收)在栈上一层的 PR 里,
 * 与那条取件链路同层。
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { HTML_PREVIEW_CSP, withHtmlPreviewCsp } from '@/session/htmlPreviewCsp';

describe('HTML_PREVIEW_CSP(策略内容)', () => {
  it('默认全拒,网络出口关闭', () => {
    expect(HTML_PREVIEW_CSP).toContain("default-src 'none'");
    expect(HTML_PREVIEW_CSP).toContain("connect-src 'none'");
    expect(HTML_PREVIEW_CSP).toContain("form-action 'none'");
    expect(HTML_PREVIEW_CSP).toContain("base-uri 'none'");
  });

  it('资源只放行 data:,不放行任何远端来源', () => {
    // 放行 img-src https: 就等于留一条 `new Image().src='…?d=…'` 外传通道,
    // 那会让「读到了也送不出去」这条保证形同虚设。
    expect(HTML_PREVIEW_CSP).toContain('img-src data:');
    expect(HTML_PREVIEW_CSP).not.toMatch(/img-src[^;]*https:/);
    expect(HTML_PREVIEW_CSP).not.toMatch(/connect-src[^;]*https:/);
    expect(HTML_PREVIEW_CSP).not.toContain('*');
  });

  it('保留内联样式与脚本(设计稿的交互依赖它)', () => {
    expect(HTML_PREVIEW_CSP).toContain("style-src 'unsafe-inline' data:");
    expect(HTML_PREVIEW_CSP).toContain("script-src 'unsafe-inline' data:");
  });
});

describe('withHtmlPreviewCsp(自带前导段,不定位作者 doctype)', () => {
  const cspAt = (out: string) => out.indexOf('<meta http-equiv');

  it('总是自己前置 doctype + 策略,原文整份跟在后面不动', () => {
    const out = withHtmlPreviewCsp('<html><body>x</body></html>');
    expect(out.startsWith('<!doctype html><meta http-equiv')).toBe(true);
    expect(out.endsWith('<html><body>x</body></html>')).toBe(true);
  });

  it('原文自带 doctype 也不去找它 —— 重复的那个按规范在 in-body 被忽略', () => {
    const out = withHtmlPreviewCsp('<!DOCTYPE html><html>x</html>');
    expect(out.startsWith('<!doctype html><meta http-equiv')).toBe(true);
    // 原文一字不动,包括它自己的 doctype。
    expect(out).toContain('<!DOCTYPE html><html>x</html>');
  });

  it('前导注释 / 处理指令 / CDATA 都不再需要认识(整类边界消失)', () => {
    // 这三种形态此前各挖过一轮:紧贴开头 → 前导注释 → 处理指令。
    for (const prefix of [
      '<!-- generated by tool -->',
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<?php echo 1; ?>',
      '<![CDATA[x]]>',
      '\n\n  <!-- a --> <!-- b -->  ',
      '<!-- 未闭合注释 ',
    ]) {
      const out = withHtmlPreviewCsp(`${prefix}<!doctype html><html>x</html>`);
      // 策略永远在最前(作者内容一律在它之后),不存在"插错位置"这回事。
      expect(out.startsWith('<!doctype html><meta http-equiv')).toBe(true);
      expect(cspAt(out)).toBeLessThan(out.indexOf(prefix));
      expect(out).toContain(prefix);
    }
  });

  it('BOM 必须前移,不能变成文档中间的游离字符', () => {
    const out = withHtmlPreviewCsp('\uFEFF<!doctype html><html>x</html>');
    expect(out.charCodeAt(0)).toBe(0xfeff);
    expect(out.slice(1).startsWith('<!doctype html><meta http-equiv')).toBe(true);
    // 只应有一个 BOM。
    expect(out.split('\uFEFF')).toHaveLength(2);
  });

  it('空文档也带策略(不留一条无策略的路径)', () => {
    expect(withHtmlPreviewCsp('').startsWith('<!doctype html><meta http-equiv')).toBe(true);
  });

  it('不去找 <head>:注释里的假标签不得成为锚点', () => {
    const out = withHtmlPreviewCsp('<!-- <head> --><html><head><title>t</title></head></html>');
    expect(out.startsWith('<!doctype html><meta http-equiv')).toBe(true);
    // 策略在假标签与真 head 之前。
    expect(cspAt(out)).toBeLessThan(out.indexOf('<!-- <head> -->'));
    expect(cspAt(out)).toBeLessThan(out.indexOf('<head>', out.indexOf('<html>')));
  });
});

describe('前导段剥离设备与 WebRTC 能力(review P0)', () => {
  const prolog = withHtmlPreviewCsp('<html><body>x</body></html>');
  const OPEN = '<script>';
  const CLOSE = '</script>';
  // 只取我们这一段:切到**第一个** </script> 为止,否则会把作者内容一起圈进来。
  const guard = prolog.slice(prolog.indexOf(OPEN), prolog.indexOf(CLOSE) + CLOSE.length);

  it('剥掉摄像头 / 麦克风入口:实例与原型都要盖,否则能沿原型链取回', () => {
    // Android 的 mediaCapturePermissionGrantType setter 是空函数(RNCWebViewManager.java),
    // 权限只看 app 级 OS 运行时权限 —— 用户为语音输入授过 RECORD_AUDIO 之后,不可信 HTML
    // 就能零提示拿到音视频流。所以能力面直接删掉,不依赖平台权限实现是否正确。
    expect(guard).toContain("hide(Navigator.prototype,'mediaDevices')".replace('Navigator.prototype', 'N'));
    expect(guard).toContain("hide(navigator,'mediaDevices')");
    expect(guard).toContain("hide(navigator,'webkitGetUserMedia')");
  });

  it('剥掉 WebRTC:iOS 上 webrtc 指令无效,删掉构造器才是真封住', () => {
    expect(guard).toContain("hide(window,'RTCPeerConnection')");
    expect(guard).toContain("hide(window,'webkitRTCPeerConnection')");
  });

  it('属性定死为不可写不可配置,作者脚本重定义会抛', () => {
    expect(guard).toContain('writable:false,configurable:false');
  });

  it('脚本在 CSP meta 之后、任何作者内容之前(无竞态)', () => {
    expect(prolog.indexOf('<meta http-equiv')).toBeLessThan(prolog.indexOf('<script>'));
    expect(prolog.indexOf('<script>')).toBeLessThan(prolog.indexOf('<html>'));
  });

  it('脚本文本不得含提前闭合的 </script>', () => {
    const body = guard.slice(OPEN.length, guard.length - CLOSE.length);
    expect(body).not.toContain('</script');
    // 整份文档里只应有我们这一个 <script>(作者内容为空时)。
    expect(prolog.split('<script>')).toHaveLength(2);
  });

  it('依赖 CSP 封掉干净 realm —— 少了这两条,作者能新开 iframe 取回原始全局', () => {
    expect(HTML_PREVIEW_CSP).toContain("frame-src 'none'");
    expect(HTML_PREVIEW_CSP).toContain("object-src 'none'");
  });

  it('不改变「预览保留 JavaScript」这个已定取舍', () => {
    // 只删设备与 WebRTC 三样,脚本执行本身照旧放行。
    expect(HTML_PREVIEW_CSP).toContain("script-src 'unsafe-inline' data:");
  });
});

describe('渲染载体的安全接线(源码级守卫)', () => {
  const readerSource = readFileSync(
    resolve(process.cwd(), 'src/session/HtmlFileReader.tsx'),
    'utf8',
  ).replace(/\r\n/g, '\n');
  const cspSource = readFileSync(
    resolve(process.cwd(), 'src/session/htmlPreviewCsp.ts'),
    'utf8',
  ).replace(/\r\n/g, '\n');

  it('CSP 挂在渲染载体上:任何进 WebView 的 HTML 都带策略', () => {
    // 放在载体这一层而不是取件那一层:不管 HTML 从哪条路来、有没有同目录资源,
    // 只要进这个 WebView 就必须带策略。
    expect(readerSource).toContain('withHtmlPreviewCsp(html)');
    expect(readerSource).toContain("source={{ baseUrl: 'about:blank', html: guardedHtml }}");
    // 不得把未加固的原文直接喂进去。
    expect(readerSource).not.toMatch(/html:\s*html\s*\}/);
  });

  it('WebRTC 是已知残留面:不得把这套说成「零出网」', () => {
    // RTCPeerConnection 的 ICE / STUN / DTLS 不受 CSP 各 *-src 指令管辖,恶意脚本能把内容
    // 编码进 STUN 域名外传(review P1)。`webrtc 'block'` 只在 Chromium 111+ 生效
    // (Android System WebView 覆盖),iOS 的 WKWebView 未实现 —— 所以 iOS 上仍有信道。
    expect(HTML_PREVIEW_CSP).toContain("webrtc 'block'");
    // 这三个说法一旦回归,就是在这个值上重建一个不成立的安全假设(同「不可伪造」那次)。
    for (const text of [readerSource, cspSource]) {
      expect(text).not.toContain('完全离线的沙箱');
      expect(text).not.toContain('完全离线的预览沙箱');
      expect(text).not.toContain('没有任何出网信道');
    }
    // 残留面必须被显式写下来,而不是靠删掉过强说法蒙过去。
    expect(cspSource).toContain('残留信道');
    expect(cspSource).toContain('WebKit');
    // 媒体权限拒绝是另一件事,注释必须说明它不是 WebRTC 的解(否则会被当成已修)。
    expect(readerSource).toContain('mediaCapturePermissionGrantType="deny"');
    expect(readerSource).toContain('不是** WebRTC 外传的解');
  });

  it('CSP 与导航策略是配套的两半:CSP 管得到的出口必须全关', () => {
    // CSP 关子资源与表单,导航回调关顶层跳转。少任何一半都留着一条外传路径
    // (review P1:导航回调完全不经过 new Image().src / fetch 这类子资源请求)。
    expect(readerSource).toContain("url.startsWith('about:')");
    expect(readerSource).not.toMatch(/\bLinking\.\w/);
    expect(HTML_PREVIEW_CSP).toContain("default-src 'none'");
    expect(HTML_PREVIEW_CSP).toContain("connect-src 'none'");
  });
});
